console.log("fichier ZH chargé!");

var listeGenerale = [
    [["闹钟"], ["nào zhōng"], ["réveil"]],
    [["球"], ["qiú"], ["balle"]],
    [["床"], ["chuáng"], ["lit"]],
    [["书架"], ["shū jià"], ["[meuble] bibliothèque"]],
    [["垃圾桶"], ["lā jī tǒng"], ["poubelle"]],
    [["地毯"], ["dì tǎn"], ["tapis"]],
    [["键盘"], ["jiàn pán"], ["clavier"]],
    [["照片"], ["zhào piàn"], ["photo"]],
    [["耳机"], ["ěr jī"], ["casque d'écoute"]],
    [["锤子"], ["chuí zi"], ["marteau"]],
    [["簸箕"], ["bò jī"], ["pelle à poussière"]],
    [["工具箱"], ["gōng jù xiāng"], ["boîte à outils"]],
    [["甜椒"], ["tián jiāo"], ["piment fort"]],
    [["番茄"], ["fān qié"], ["tomate"]],
    [["胡萝卜"], ["hú luó bo"], ["carotte"]],
    [["香蕉"], ["xiāng jiāo"], ["banane"]],
    [["蓝莓"], ["lán méi"], ["airelles / myrtilles"]],
    [["桃子"], ["táo zi"], ["pêche"]],
    [["钱包"], ["qián bāo"], ["portefeuille"]],
    [["刀"], ["dāo"], ["couteau"]],
    [["微波炉"], ["wéi bō lú"], ["four micro-ondes"]],
    [["冰箱"], ["bīng xiāng"], ["réfrigérateur"]],
    [["勺子"], ["sháo zi"], ["cuillère"]],
    [["碗"], ["wǎn"], ["bol"]],
    [["搅拌机"], ["jiǎo bàn jī"], ["mixer de cuisine"]],
    [["蜡烛"], ["là zhú"], ["bougie"]],
    [["眼镜"], ["yǎn jìng"], ["les lunettes"]],
    [["打火机"], ["dǎ huǒ jī"], ["briquet"]],
    [["卫生纸"], ["wèi shēng zhǐ"], ["papier toilette"]],
    [["伞"], ["sǎn"], ["parapluie"]],
    [["海报"], ["hǎi bào"], ["poster"]],
    [["玩具"], ["wán jù"], ["jouet"]],
    [["红酒"], ["hóng jiǔ"], ["vin rouge"]],
    [["袜子"], ["wà zi"], ["chaussette"]],
    [["插座"], ["chā zuò"], ["prise de courant"]],
    [["毛巾"], ["máo jīn"], ["serviette"]],
    [["可是"], ["kě shì"], ["mais"]],
    [["衬衫"], ["chèn shān"], ["chemise"]],
    [["衣柜"], ["yī guì"], ["armoire (pour les vêtements)"]],
    [["锅"], ["guō"], ["marmite"]],
    [["游戏"], ["yóu xì"], ["jeu"]],
    [["仙人掌"], ["xiān rén zhǎng"], ["cactus"]],
    [["杂志"], ["zá zhì"], ["magazine"]],
    [["日历"], ["rì lì"], ["calendrier"]],
    [["光碟"], ["guāng dié"], ["CD"]],
    [["烤面包机"], ["kǎo miàn bāo jī"], ["grille-pain"]],
    [["这是什么？"], ["zhè shì shénme?"], ["qu'est-ce que c'est?"]],
    [["苏打水"], ["sū dá shuǐ"], ["soda"]],
    [["凉拖"], ["liáng tuō"], ["sandale"]],
    [["门把手"], ["mén bǎ shǒu"], ["poignée de porte"]],
    [["纸巾"], ["zhǐ jīn"], ["mouchoir"]],
    [["棒球"], ["bàng qiú"], ["balle de base-ball"]],
    [["游戏机"], ["yóu xì jī"], ["console de jeux"]],
    [["拖鞋"], ["tuō xié"], ["pantoufles"]],
    [["智能的"], ["zhì néng de"], ["[téléphone] intelligent"]],
    [["谷物"], ["gǔ wù"], ["céréales"]],
    [["筷子"], ["kuài zi"], ["baguettes"]],
    [["罐头"], ["guàn tou"], ["canette"]],
    [["混合"], ["hùn hé"], ["mélanger"]],
    [["休闲的"], ["xiū xián de"], ["décontracté"]],
    [["鞋"], ["xié"], ["chaussure"]],
    [["灯"], ["dēng"], ["lampe"]],
    [["高"], ["gāo"], ["haut"]],
    [["马桶"], ["mǎ tǒng"], ["[meuble] toilette"]],
    [["内裤"], ["nèi kù"], ["sous-vêtements"]],
    [["打开"], ["dǎ kāi"], ["ouvrir"]],
    [["牙膏"], ["yá gāo"], ["dentifrice"]],
    [["杆"], ["gān"], ["tringle"]],
    [["窗帘"], ["chuāng lián"], ["rideaux"]],
    [["牙刷"], ["yá shuā"], ["brosse à dents"]],
    [["牙线"], ["yá xiàn"], ["fil dentaire"]],
    [["肥皂"], ["féi zào"], ["savon"]],
    [["肥皂盒"], ["féi zào hé"], ["porte-savon"]],
    [["洗发水"], ["xǐ fà shuǐ"], ["shampoing"]],
    [["剃刀"], ["tì dāo"], ["rasoir"]],
    [["剃"], ["tì"], ["raser"]],
    [["杯垫"], ["bēi diàn"], ["sous-verre"]],
    [["奶酪"], ["nǎi lào"], ["fromage"]],
    [["按班"], ["àn bān"], ["planche à découper"]],
    [["油腻的"], ["yóu nì de"], ["gras"]],
    [["木质的"], ["mù zhì de"], ["en bois"]],
    [["玉米"], ["yù mǐ"], ["maïs"]],
    [["叉子"], ["chā zi"], ["fourchette"]],
    [["南瓜"], ["nán guā"], ["citrouille"]],
    [["草莓"], ["cǎo méi"], ["fraise"]],
    [["鱼肉"], ["yú ròu"], ["chair de poisson"]],
    [["忘记"], ["wàng jì"], ["oublier"]],
    [["凉爽的"], ["liáng shuǎng de"], ["frais"]],
    [["蛋黄酱"], ["dàn huáng jiàng"], ["mayonnaise"]],
    [["可爱的"], ["kě ài de"], ["mignon"]],
    [["骰子"], ["tóu zi"], ["dé à jouer"]],
    [["月饼"], ["yùe bǐng"], ["gâteau de lune"]],
    [["饼"], ["bǐng"], ["gâteau"]],
    [["蛋糕"], ["dàn gāo"], ["gâteau"]],
    [["啤酒"], ["pí jiǔ"], ["bière"]],
    [["珍珠奶茶"], ["zhēn zhū nǎi chá"], ["bubble tea"]],
    [["火"], ["huǒ"], ["feu"]],
    [["工具"], ["gōng jù"], ["outil"]],
    [["螺丝刀"], ["luó sī dāo"], ["tournevis"]],
    [["厕所"], ["cè suǒ"], ["toilettes"]],
    [["女朋友"], ["nǚ péng you"], ["petite amie"]],
    [["喂?"], ["wèi?"], ["allô?"]],
    [["哪里"], ["nǎ lǐ"], ["où"]],
    [["讲价"], ["jiǎng jià"], ["marchander"]],
    [["写下来"], ["xiě xià lái"], ["écrivez-le"]],
    [["买单!"], ["mǎi dān!"], ["l'addition!"]],
    [["你多大?"], ["nĭ duō dà?"], ["quel âge as-tu?"]],
    [["我很小"], ["wǒ hěn xiǎo"], ["je suis très jeune"]],
    [["欢迎"], ["huān yíng"], ["bienvenue"]],
    [["自行车"], ["zì xíng chē"], ["vélo"]],
    [["车"], ["chē"], ["voiture"]],
    [["要"], ["yào"], ["vouloir"]],
    [["游泳"], ["yóu yǒng"], ["nager"]],
    [["走路"], ["zǒu lù"], ["marcher"]],
    [["敢"], ["gǎn"], ["oser"]],
    [["明白"], ["míng bai"], ["comprendre"]],
    [["说"], ["shuō"], ["parler"]],
    [["知道"], ["zhī dào"], ["savoir"]],
    [["灰色"], ["huī sè"], ["gris"]],
    [["头发"], ["tóu fa"], ["cheveux"]],
    [["做饭"], ["zuò fàn"], ["faire à manger"]],
    [["我在"], ["wǒ zài"], ["je suis en train de..."]],
    [["果汁"], ["guǒ zhī"], ["jus de fruit"]],
    [["你在做什么?"], ["nǐ zài zuò shén me?"], ["qu'est-ce que tu fais?"]],
    [["你找哪位?"], ["nĭ zhǎo nǎ wèi?"], ["c'est pour qui?"]],
    [["星期一"], ["xīng qī yī"], ["lundi"]],
    [["星期二"], ["xīng qī èr"], ["mardi"]],
    [["星期三"], ["xīng qī sān"], ["mercredi"]],
    [["星期四"], ["xīng qī sì"], ["jeudi"]],
    [["星期五"], ["xīng qī wǔ"], ["vendredi"]],
    [["星期六"], ["xīng qī liù"], ["samedi"]],
    [["星期天"], ["xīng qī tiān"], ["dimanche"]],
    [["一月"], ["yī yuè"], ["janvier"]],
    [["二月"], ["èr yuè"], ["février"]],
    [["三月"], ["sān yuè"], ["mars"]],
    [["四月"], ["sì yuè"], ["avril"]],
    [["五月"], ["wǔ yuè"], ["mai"]],
    [["六月"], ["liù yuè"], ["juin"]],
    [["七月"], ["qī yuè"], ["juillet"]],
    [["八月"], ["bā yuè"], ["août"]],
    [["九月"], ["jiǔ yuè"], ["septembre"]],
    [["十月"], ["shí yuè"], ["octobre"]],
    [["十二月"], ["shí èr yuè"], ["décembre"]],
    [["十一月"], ["shí yī yuè"], ["novembre"]],
    [["太贵了"], ["tài guì le"], ["trop cher"]],
    [["晚安!"], ["wǎn ān!"], ["bonne nuit!"]],
    [["床头柜"], ["chuáng tóu guì"], ["table de nuit"]],
    [["台灯"], ["tái dēng"], ["lampe de bureau"]],
    [["裤子"], ["kù zi"], ["pantalon"]],
    [["滑板"], ["huá bǎn"], ["skate"]],
    [["毛毯"], ["máo tǎn"], ["couverture"]],
    [["棒"], ["bàng"], ["bâton"]],
    [["棒球棒"], ["bàng qiú bàng"], ["batte de base-ball"]],
    [["药丸"], ["yào wán"], ["pilule"]],
    [["围巾"], ["wéi jīn "], ["foulard"]],
    [["存钱罐"], ["cún qián guàn"], ["tirelire"]],
    [["意大利面"], ["yì dà lì miàn"], ["pâtes"]],
    [["食盐"], ["shí yán"], ["sel de table"]],
    [["磁铁"], ["cí tiě"], ["aimant"]],
    [["淋浴器"], ["lín yù qì"], ["douche"]],
    [["窗户"], ["chuāng hu"], ["fenêtre"]],
    [["植物"], ["zhí wù"], ["plante"]],
    [["名片"], ["míng piàn"], ["carte de visite"]],
    [["鼠标"], ["shǔ biāo"], ["souris d'ordinateur"]],
    [["扫帚"], ["sào zhou"], ["balai"]],
    [["放大器"], ["fàng dà qì"], ["amplificateur"]],
    [["遥控器"], ["yáo kòng qì"], ["télécommande"]],
    [["手提箱"], ["shǒu tí xiāng"], ["valise"]],
    [["土壤"], ["tǔ rǎng"], ["terre"]],
    [["薯片"], ["shǔ piàn"], ["(pommes) chips"]],
    [["电池"], ["diàn chí"], ["pile"]],
    [["剪刀"], ["jiǎn dāo"], ["ciseaux"]],
    [["维他命"], ["wéi tā mìng"], ["vitamine"]],
    [["电饭煲"], ["diàn fàn bāo"], ["cuiseur à riz"]],
    [["脸盆"], ["liǎn pén"], ["bac d'évier"]],
    [["盖"], ["gài"], ["couvercle"]],
    [["干净的"], ["gān jìng de"], ["propre"]],
    [["火柴"], ["huǒ chái"], ["allumette"]],
    [["可燃的"], ["kě rán de"], ["inflammable"]],
    [["把手"], ["bǎ shǒu"], ["poignée"]],
    [["管子"], ["guǎn zi"], ["tuyau"]],
    [["吸尘器"], ["xī chén qì"], ["aspirateur"]],
    [["衣架"], ["yī jià"], ["cintre"]],
    [["酸奶"], ["suān nǎi"], ["yaourt"]],
    [["不健康"], ["bù jiàn kāng"], ["malsain"]],
    [["坚果"], ["jiān guǒ"], ["noix"]],
    [["扳手"], ["bān shǒu"], ["clé anglaise"]],
    [["打印机"], ["dǎ yìn jī"], ["imprimante"]],
    [["计划"], ["jì huà"], ["planifier"]],
    [["挂"], ["guà"], ["accrocher"]],
    [["喷雾瓶"], ["pēn wù píng"], ["vaporisateur"]],
    [["喷洒"], ["pēn sǎ"], ["vaporiser"]],
    [["订书机"], ["dìng shū jī"], ["agrafeuse"]],
    [["电话"], ["diàn huà"], ["téléphone"]],
    [["挂电话"], ["guà diàn huà"], ["raccrocher le téléphone"]],
    [["你先挂"], ["nĭ xiān guà"], ["raccroche en premier!"]],
    [["你没事吧?"], ["nǐ méi shì ba?"], ["rien de cassé?"]],
    [["画"], ["huà"], ["peinture"]],
    [["垫子"], ["diàn zi"], ["paillasson"]],
    [["护发素"], ["hù fà sù"], ["revitalisant"]],
    [["排水口"], ["pái shuǐ kǒu"], ["drain"]],
    [["镜"], ["jìng"], ["miroir"]],
    [["橱柜"], ["chú guì"], ["placard mural"]],
    [["厕位"], ["cè wèi"], ["lunette des toilettes"]],
    [["盥洗台"], ["guàn xǐ tái"], ["évier"]],
    [["梳子"], ["shū zi"], ["brosse à cheveux"]],
    [["水龙头"], ["shuǐ lóng tóu"], ["robinet"]],
    [["水壶"], ["shuǐ hú"], ["bouilloire"]],
    [["门"], ["mén"], ["porte"]],
    [["除臭剂"], ["chú chòu jì"], ["déodorant (personnel)"]],
    [["绷带"], ["bēng dài"], ["pansement adhésif"]],
    [["划妆水"], ["huà zhuāng shuǐ"], ["crème"]],
    [["空气清新器"], ["kōng qì qīng xīn qì"], ["désodorisant de toilettes"]],
    [["你们"], ["nǐ men"], ["vous pluriel"]],
    [["她们"], ["tā men"], ["elles"]],
    [["这儿"], ["zhèr"], ["ici"]],
    [["帽子"], ["mào zi"], ["chapeau"]],
    [["上"], ["shàng"], ["sur"]],
    [["下"], ["xià"], ["sous"]],
    [["手"], ["shǒu"], ["main"]],
    [["右首"], ["yòu shǒu"], ["main droite"]],
    [["左手"], ["zuǒ shǒu"], ["main gauche"]],
    [["收音机"], ["shōu yīn jī"], ["radio"]],
    [["房間"], ["fáng jiān"], ["pièce"]],
    [["瓶子"], ["píng zi"], ["bouteille"]],
    [["也"], ["yě"], ["aussi"]],
    [["鸟"], ["niǎo"], ["oiseau"]],
    [["脚"], ["jiǎo"], ["pied"]],
    [["胳膊"], ["gē bo"], ["bras"]],
    [["关"], ["guān"], ["fermer"]],
    [["开着"], ["kāi zhe"], ["ouvert"]],
    [["体恤衫"], ["tǐ xù shān"], ["t-shirt"]],
    [["裙子"], ["qún zi"], ["jupe"]],
    [["穿着"], ["chuānzhe"], ["porter (un vêtement)"]],
    [["钥匙扣"], ["yào shi kòu"], ["porte-clés"]],
    [["钥匙"], ["yào shi"], ["clé"]],
    [["枕头"], ["zhěn tou"], ["oreiller"]],
    [["床垫"], ["chuáng diàn"], ["matelas"]],
    [["床架"], ["chuáng jià"], ["sommier"]],
    [["空调"], ["kōng tiáo"], ["(clim)atisation"]],
    [["棒球手套"], ["bàng qiú shǒu tào"], ["gant de base-ball"]],
    [["洗衣篮"], ["xǐ yī lán"], ["panier à linge"]],
    [["门框"], ["mén kuàng"], ["cadre de porte"]],
    [["洗衣液"], ["xǐ yī yè"], ["lessive"]],
    [["照明开關"], ["zhào míng kāi guān"], ["interrupteur"]],
    [["领带"], ["lǐng dài"], ["cravate"]],
    [["托盘"], ["tuō pán"], ["plateau"]],
    [["漫画书"], ["màn huà shū"], ["bande dessinée"]],
    [["天花板"], ["tiān huā bǎn"], ["plafond"]],
    [["紙"], ["zhǐ"], ["papier"]],
    [["书桌"], ["shū zhuō"], ["[meuble] bureau"]],
    [["报告"], ["bào gào"], ["rapport"]],
    [["留言板"], ["li­ú yán bǎn"], ["tableau d'affichage"]],
    [["花盆"], ["huā pén"], ["pot à fleurs"]],
    [["叶"], ["yè"], ["feuille (de plante)"]],
    [["便条"], ["biàn tiáo"], ["Post-it"]],
    [["药店"], ["yào diàn"], ["pharmacie"]],
    [["淋浴龙头"], ["lín yù lóng tóu"], ["pommeau de douche"]],
    [["扬声器"], ["yáng shēng qì"], ["haut-parleur"]],
    [["显示器"], ["xiǎn shì qì"], ["moniteur"]],
    [["圆珠笔"], ["yuán zhū bǐ"], ["stylo à bille"]],
    [["鉛筆"], ["qiān bǐ"], ["crayon à papier"]],
    [["衣帽勾"], ["yī mào gōu"], ["porte-manteau"]],
    [["传单"], ["chuán dān"], ["prospectus"]],
    [["面粉"], ["miàn fěn"], ["farine"]],
    [["洗碗机"], ["xǐ wǎn jī"], ["lave-vaisselle"]],
    [["茶杯"], ["chá bēi"], ["tasse à thé"]],
    [["三明治"], ["sān míng zhì"], ["sandwich"]],
    [["盘子"], ["pán zi"], ["assiette"]],
    [["松饼"], ["sōng bǐng"], ["muffin"]],
    [["平底锅"], ["píng dǐ guō"], ["poêle à frire"]],
    [["锅鏟"], ["guō chǎn"], ["spatule"]],
    [["炉子"], ["lú zi"], ["table de cuisson"]],
    [["旋钮"], ["xuán niǔ"], ["bouton (tournant)"]],
    [["烤箱"], ["kǎo xiāng"], ["four"]],
    [["面板"], ["miàn bǎn"], ["panneau de commandes"]],
    [["炉头"], ["lú tou"], ["plaque chauffante, rond"]],
    [["食用油"], ["shí yòng yóu"], ["huile de cuisson"]],
    [["罐"], ["guàn"], ["pot"]],
    [["抽油烟机"], ["chōu yóu yān jī"], ["hotte de cuisine"]],
    [["擦手纸"], ["cā shǒu zhǐ"], ["essuie-tout"]],
    [["橙子"], ["chéng zi"], ["orange"]],
    [["桔子"], ["jú zi"], ["tangerine"]],
    [["拖把"], ["tuō bǎ"], ["balai à franges / balai-éponge"]],
    [["烤盘"], ["kǎo pán"], ["plaque de cuisson"]],
    [["派"], ["pài"], ["tarte"]],
    [["烤箱架"], ["kǎo xiāng jià"], ["grille de four"]],
    [["洋葱"], ["yáng cōng"], ["oignon"]],
    [["土豆"], ["tǔ dòu"], ["[familier] patate, pomme de terre"]],
    [["番茄酱"], ["fān qié jiàng"], ["ketchup"]],
    [["冰淇淋"], ["bīng qí lín"], ["crème glacée, glace"]],
    [["冰棍"], ["bīng gùn"], ["sucette glacée"]],
    [["黄油"], ["huáng yóu"], ["beurre"]],
    [["芥末"], ["jiè mo"], ["moutarde"]],
    [["醋"], ["cù"], ["vinaigre"]],
    [["酱油"], ["jiàng yóu"], ["sauce soja"]],
    [["果酱"], ["guǒ jiàng"], ["confiture"]],
    [["樱桃"], ["yīng táo"], ["cerise"]],
    [["猪肉"], ["zhū ròu"], ["chair de porc"]],
    [["牛肉"], ["niú ròu"], ["chair de boeuf"]],
    [["椰子"], ["yē zi"], ["noix de coco"]],
    [["蘑菇"], ["mó gū"], ["champignon"]],
    [["葡萄"], ["pú tao"], ["raisin"]],
    [["卷心菜"], ["juǎn xīn cài"], ["chou"]],
    [["茄子"], ["qié zi"], ["aubergine"]],
    [["黄瓜"], ["huáng guā"], ["concombre"]],
    [["芹菜"], ["qín cài"], ["céleri"]],
    [["青柠"], ["qīng níng"], ["lime"]],
    [["柠檬"], ["níng méng"], ["citron"]],
    [["罗勒"], ["luó lè"], ["basilic"]],
    [["桂香"], ["guì xiāng"], ["cannelle"]],
    [["胡椒"], ["hú jiāo"], ["poivre"]],
    [["橡皮"], ["xiàng pí"], ["gomme à effacer"]],
    [["马克笔"], ["mǎ kè bǐ"], ["marqueur"]],
    [["餐巾纸"], ["cān jīn zhǐ"], ["serviette de table"]],
    [["饼干"], ["bǐng gān"], ["biscuit"]],
    [["菠萝"], ["bō luó"], ["ananas"]],
    [["保鲜膜"], ["bǎo xiān mó"], ["pellicule plastique"]],
    [["擀面杖"], ["gǎn miàn zhàng"], ["rouleau à pâtisserie"]],
    [["开罐器"], ["kāi guàn qì"], ["ouvre-boîte"]],
    [["开瓶器"], ["kāi píng qì"], ["ouvre-bouteille"]],
    [["马克杯"], ["mǎ kè bēi"], ["(grande) tasse  "]],
    [["沙发"], ["shā fā"], ["canapé, sofa"]],
    [["手柄"], ["shǒu bǐng"], ["manette"]],
    [["足球"], ["zú qiú"], ["ballon rond"]],
    [["百叶帘"], ["bǎi yè lián"], ["stores"]],
    [["吉他"], ["jí tā"], ["guitare"]],
    [["烟灰缸"], ["yān huī gāng"], ["cendrier"]],
    [["香"], ["xiāng"], ["encens"]],
    [["电视柜"], ["diàn shì guì"], ["meuble de télévision"]],
    [["DVD播放机"], ["DVD bō fàng jī"], ["lecteur DVD"]],
    [["吊扇"], ["diào shàn"], ["ventilateur de plafond"]],
    [["壁橱"], ["bì chú"], ["penderie"]],
    [["运动衫"], ["yùn dòng shān"], ["sweatshirt"]],
    [["上衣"], ["shàng yī"], ["veste de costume"]],
    [["美丽的"], ["měi lì de"], ["beau"]],
    [["冲洗"], ["chōng xǐ"], ["tirer la chasse"]],
    [["充电"], ["chōng diàn"], ["recharger des piles"]],
    [["低"], ["dī"], ["bas"]],
    [["站立"], ["zhàn lì"], ["être debout"]],
    [["照亮"], ["zhào liàng"], ["éclairer"]],
    [["刷"], ["shuā"], ["brosser"]],
    [["金币的"], ["jǐn bì de"], ["fermé"]],
    [["芳香的"], ["fāng xiāng de"], ["parfumé"]],
    [["治疗"], ["zhì liáo"], ["guérir"]],
    [["呼叫"], ["hū jiào"], ["appeler (par téléphone)"]],
    [["金属的"], ["jīn shǔ de"], ["métallique"]],
    [["击打"], ["jī dǎ"], ["frapper"]],
    [["消去"], ["xiāo qù"], ["effacer"]],
    [["扫"], ["sǎo"], ["balayer"]],
    [["依靠"], ["yǐ kào"], ["se fier à"]],
    [["穿"], ["chuān"], ["mettre (un vêtement)"]],
    [["存放"], ["cún fàng"], ["entreposer"]],
    [["接"], ["jiē"], ["attraper"]]
];

/*
var questionsReponses = [
    [["我"], ["wǒ"], ["I, me"]],
    [["我们"], ["wǒmen"], ["we, us （pl.）"]],
    [["你"], ["nǐ"], ["you"]],
    ];
*/

/*
var questionsReponses = [
    [["阿姨"], ["āyí"], ["aunt"]],
    [["啊"], ["a"], ["ah"]],
    [["矮"], ["ǎi"], ["short"]],
    [["爱"], ["ài"], ["love"]],
    [["爱好"], ["àihào"], ["hobby"]],
    [["安静"], ["ānjìng"], ["Be quiet"]],
    [["八"], ["bā"], ["Eight"]],
    [["把"], ["bǎ"], ["hold"]],
    [["爸爸"], ["bàba"], ["Dad"]],
    [["吧"], ["ba"], [""]],
    [["白"], ["bái"], ["white"]],
    [["百"], ["bǎi"], ["hundred"]],
    [["班"], ["bān"], ["class"]],
    [["搬"], ["bān"], ["to move"]],
    [["半"], ["bàn"], ["half"]],
    [["办法"], ["bànfǎ"], ["Way"]],
    [["办公室"], ["bàngōngshì"], ["Office"]],
    [["帮忙"], ["bāngmáng"], ["Help"]],
    [["帮助"], ["bāngzhù"], ["Help"]],
    [["包"], ["bāo"], ["bag"]],
    [["饱"], ["bǎo"], ["full"]],
    [["报纸"], ["bàozhǐ"], ["Newspaper"]],
    [["杯子"], ["bēizi"], ["glass"]],
    [["北方"], ["běifāng"], ["north"]],
    [["北京"], ["běijīng"], ["Beijing"]],
    [["被"], ["bèi"], ["by / to cover"]],
    [["本"], ["běn"], ["book"]],
    [["鼻子"], ["bízi"], ["nose"]],
    [["比"], ["bǐ"], ["than"]],
    [["比较"], ["bǐjiào"], ["comparatively / to compare"]],
    [["比赛"], ["bǐsài"], ["Match"]],
    [["必须"], ["bìxū"], ["Compulsory / to have to"]],
    [["变化"], ["biànhuà"], ["change"]],
    [["表示"], ["biǎoshì"], ["Express"]],
    [["表演"], ["biǎoyǎn"], ["perform"]],
    [["别"], ["bié"], ["other"]],
    [["别人"], ["biéren"], ["Others"]],
    [["宾馆"], ["bīnguǎn"], ["hotel"]],
    [["冰箱"], ["bīngxiāng"], ["Refrigerator"]],
    [["不客气"], ["búkèqi"], ["You are welcome"]],
    [["不"], ["bù"], ["No"]],
    [["才"], ["cái"], ["just"]],
    [["菜"], ["cài"], ["food"]],
    [["菜单"], ["càidān"], ["menu"]],
    [["参加"], ["cānjiā"], ["participate in"]],
    [["草"], ["cǎo"], ["grass"]],
    [["层"], ["céng"], ["layer"]],
    [["茶"], ["chá"], ["tea"]],
    [["差"], ["chà"], ["difference"]],
    [["长"], ["cháng"], ["long"]],
    [["唱歌"], ["chànggē"], ["Sing"]],
    [["超市"], ["chāoshì"], ["Supermarket"]],
    [["衬衫"], ["chènshān"], ["shirt"]],
    [["成绩"], ["chéngjì"], ["achievement; grades"]],
    [["城市"], ["chéngshì"], ["City"]],
    [["吃"], ["chī"], ["eat"]],
    [["迟到"], ["chídào"], ["Late"]],
    [["出"], ["chū"], ["come out"]],
    [["出现"], ["chūxiàn"], ["Appear"]],
    [["出租车"], ["chūzūchē"], ["Taxi"]],
    [["厨房"], ["chúfáng"], ["Kitchen"]],
    [["除了"], ["chúle"], ["besides / except for"]],
    [["穿"], ["chuān"], ["to wear"]],
    [["船"], ["chuán"], ["ship"]],
    [["春"], ["chūn"], ["spring"]],
    [["词语"], ["cíyǔ"], ["terms"]],
    [["次"], ["cì"], ["second"]],
    [["聪明"], ["cōngming"], ["clever"]],
    [["从"], ["cóng"], ["from"]],
    [["错"], ["cuò"], ["Wrong"]],
    [["打电话"], ["dǎdiànhuà"], ["Phone"]],
    [["打篮球"], ["dǎlánqiú"], ["Play basketball"]],
    [["打扫"], ["dǎsǎo"], ["Clean"]],
    [["打算"], ["dǎsuàn"], ["Plan"]],
    [["大"], ["dà"], ["large"]],
    [["大家"], ["dàjiā"], ["everybody"]],
    [["带"], ["dài"], ["belt"]],
    [["担心"], ["dānxīn"], ["Worry"]],
    [["蛋糕"], ["dàngāo"], ["Cake"]],
    [["但是"], ["dànshì"], ["however"]],
    [["当然"], ["dāngrán"], ["Of course"]],
    [["到"], ["dào"], ["reach"]],
    [["地"], ["de"], ["particle"]],
    [["的"], ["de"], ["particle"]],
    [["得"], ["de"], ["particle"]],
    [["灯"], ["dēng"], ["lamp"]],
    [["等"], ["děng"], ["etc."]],
    [["低"], ["dī"], ["low"]],
    [["弟弟"], ["dìdi"], ["younger brother"]],
    [["地方"], ["dìfang"], ["local"]],
    [["地铁"], ["dìtiě"], ["metro"]],
    [["地图"], ["dìtú"], ["Map"]],
    [["第一"], ["dìyī"], ["first"]],
    [["点"], ["diǎn"], ["spot"]],
    [["电脑"], ["diànnǎo"], ["Computer"]],
    [["电视"], ["diànshì"], ["television"]],
    [["电梯"], ["diàntī"], ["elevator"]],
    [["电影"], ["diànyǐng"], ["Film"]],
    [["电子邮件"], ["diànzǐyóujiàn"], ["E-mail"]],
    [["东"], ["dōng"], ["east"]],
    [["东西"], ["dōngxi"], ["thing"]],
    [["冬"], ["dōng"], ["winter"]],
    [["懂"], ["dǒng"], ["understand"]],
    [["动物"], ["dòngwù"], ["Animal"]],
    [["都"], ["dōu"], ["all"]],
    [["读"], ["dú"], ["read"]],
    [["短"], ["duǎn"], ["short"]],
    [["段"], ["duàn"], ["paragraph"]],
    [["锻炼"], ["duànliàn"], ["to work out / to engage in physical exercise"]],
    [["对"], ["duì"], ["Yes"]],
    [["对不起"], ["duìbuqǐ"], ["I’m sorry."]],
    [["多"], ["duō"], ["many"]],
    [["多么"], ["duōme"], ["what a...!"]],
    [["多少"], ["duōshao"], ["how much"]],
    [["饿"], ["è"], ["hungry"]],
    [["而且"], ["érqiě"], ["moreover / in addition / furthermore"]],
    [["儿子"], ["érzi"], ["Son"]],
    [["耳朵"], ["ěrduo"], ["Ears"]],
    [["二"], ["èr"], ["Two"]],
    [["发烧"], ["fāshāo"], ["Have a fever"]],
    [["发现"], ["fāxiàn"], ["find"]],
    [["饭馆"], ["fànguǎn"], ["restaurant"]],
    [["方便"], ["fāngbiàn"], ["convenient"]],
    [["房间"], ["fángjiān"], ["Room"]],
    [["放"], ["fàng"], ["discharge"]],
    [["放心"], ["fàngxīn"], ["Don’t worry"]],
    [["非常"], ["fēicháng"], ["very"]],
    [["飞机"], ["fēijī"], ["aircraft"]],
    [["分"], ["fēn"], ["branch"]],
    [["分钟"], ["fēnzhōng"], ["minute"]],
    [["服务员"], ["fúwùyuán"], ["waiter"]],
    [["附近"], ["fùjìn"], ["nearby"]],
    [["复习"], ["fùxí"], ["Review"]],
    [["干净"], ["gānjìng"], ["clean"]],
    [["敢"], ["gǎn"], ["dare"]],
    [["感冒"], ["gǎnmào"], ["Cold"]],
    [["刚才"], ["gāngcái"], ["just now / a moment ago"]],
    [["高"], ["gāo"], ["high"]],
    [["高兴"], ["gāoxìng"], ["happy"]],
    [["告诉"], ["gàosu"], ["tell"]],
    [["哥哥"], ["gēge"], ["brother"]],
    [["个"], ["gè"], ["classifier for people of objects in general"]],
    [["给"], ["gěi"], ["to"]],
    [["跟"], ["gēn"], ["with"]],
    [["根据"], ["gēnjù"], ["according to"]],
    [["更"], ["gèng"], ["more"]],
    [["公共汽车"], ["gōnggòngqìchē"], ["Bus"]],
    [["公斤"], ["gōngjīn"], ["Kg."]],
    [["公司"], ["gōngsī"], ["company"]],
    [["公园"], ["gōngyuán"], ["Park"]],
    [["工作"], ["gōngzuò"], ["work"]],
    [["狗"], ["gǒu"], ["Dog"]],
    [["故事"], ["gùshi"], ["Story"]],
    [["刮风"], ["guāfēng"], ["to be windy"]],
    [["关"], ["guān"], ["shut"]],
    [["关系"], ["guānxì"], ["relationship"]],
    [["关心"], ["guānxīn"], ["Care for"]],
    [["关于"], ["guānyú"], ["about"]],
    [["贵"], ["guì"], ["Expensive"]],
    [["国家"], ["guójiā"], ["Country"]],
    [["果汁"], ["guǒzhī"], ["fruit juice"]],
    [["过去"], ["guòqù"], ["Past times"]],
    [["过"], ["guo"], ["too"]],
    [["还"], ["hái"], ["still"]],
    [["还是"], ["háishì"], ["still"]],
    [["孩子"], ["háizi"], ["Children"]],
    [["害怕"], ["hàipà"], ["Fear"]],
    [["汉语"], ["hànyǔ"], ["Chinese"]],
    [["好"], ["hǎo"], ["good"]],
    [["好吃"], ["hǎochī"], ["Yummy"]],
    [["号"], ["hào"], ["Number"]],
    [["喝"], ["hē"], ["to drink"]],
    [["和"], ["hé"], ["and"]],
    [["河"], ["hé"], ["river"]],
    [["黑"], ["hēi"], ["black"]],
    [["黑板"], ["hēibǎn"], ["blackboard"]],
    [["很"], ["hěn"], ["very"]],
    [["红"], ["hóng"], ["red"]],
    [["后面"], ["hòumiàn"], ["behind"]],
    [["护照"], ["hùzhào"], ["passport"]],
    [["花 （动）"], ["huā"], ["Flower (move)"]],
    [["花园"], ["huāyuán"], ["Garden"]],
    [["画"], ["huà"], ["painting"]],
    [["坏"], ["huài"], ["bad"]],
    [["欢迎"], ["huānyíng"], ["Welcome"]],
    [["还"], ["huán"], ["still"]],
    [["环境"], ["huánjìng"], ["Environmental Science"]],
    [["换"], ["huàn"], ["change"]],
    [["黄"], ["huáng"], ["yellow"]],
    [["回"], ["huí"], ["return"]],
    [["回答"], ["huídá"], ["Answer"]],
    [["会"], ["huì"], ["can；be able to"]],
    [["会议"], ["huìyì"], ["Meeting"]],
    [["火车站"], ["huǒchēzhàn"], ["Train station"]],
    [["或者"], ["huòzhě"], ["perhaps"]],
    [["机场"], ["jīchǎng"], ["Airport"]],
    [["鸡蛋"], ["jīdàn"], ["Egg"]],
    [["几乎"], ["jīhū"], ["almost"]],
    [["机会"], ["jīhuì"], ["Opportunity"]],
    [["极"], ["jí"], ["extremely"]],
    [["几"], ["jǐ"], ["several"]],
    [["记得"], ["jìde"], ["remember"]],
    [["季节"], ["jìjié"], ["Season"]],
    [["家"], ["jiā"], ["home"]],
    [["检查"], ["jiǎnchá"], ["inspection / to inspect"]],
    [["简单"], ["jiǎndān"], ["not complicated / simple"]],
    [["件"], ["jiàn"], ["piece"]],
    [["健康"], ["jiànkāng"], ["Healthy"]],
    [["见面"], ["jiànmiàn"], ["to meet"]],
    [["讲"], ["jiǎng"], ["to speak / to explain / to negotiate / to emphasise / to be particular about / as far as sth is concerned / speech / lecture"]],
    [["教"], ["jiāo"], ["teach"]],
    [["角"], ["jiǎo"], ["horn"]],
    [["脚"], ["jiǎo"], ["foot"]],
    [["叫"], ["jiào"], ["call"]],
    [["教室"], ["jiàoshì"], ["Classroom"]],
    [["接"], ["jiē"], ["meet"]],
    [["街道"], ["jiēdào"], ["Street"]],
    [["结婚"], ["jiéhūn"], ["marry"]],
    [["结束"], ["jiéshù"], ["to end"]],
    [["节目"], ["jiémù"], ["program"]],
    [["节日"], ["jiérì"], ["festival"]],
    [["姐姐"], ["jiějie"], ["sister"]],
    [["解决"], ["jiějué"], ["Solve"]],
    [["借"], ["jiè"], ["borrow"]],
    [["介绍"], ["jièshào"], ["to introduce"]],
    [["今天"], ["jīntiān"], ["Today"]],
    [["进"], ["jìn"], ["enter"]],
    [["近"], ["jìn"], ["near"]],
    [["经常"], ["jīngcháng"], ["Often"]],
    [["经过"], ["jīngguò"], ["after"]],
    [["经理"], ["jīnglǐ"], ["manager"]],
    [["九"], ["jiǔ"], ["Nine"]],
    [["久"], ["jiǔ"], ["long"]],
    [["旧"], ["jiù"], ["used"]],
    [["就"], ["jiù"], [""]],
    [["举行"], ["jǔxíng"], ["to hold (a meeting, ceremony etc.)"]],
    [["句子"], ["jùzi"], ["sentence"]],
    [["觉得"], ["juéde"], ["to think / to feel"]],
    [["决定"], ["juédìng"], ["Decision"]],
    [["咖啡"], ["kāfēi"], ["Coffee"]],
    [["开"], ["kāi"], ["open"]],
    [["开始"], ["kāishǐ"], ["start"]],
    [["看"], ["kàn"], ["see"]],
    [["看见"], ["kànjiàn"], ["to see / to catch sight of"]],
    [["考试"], ["kǎoshì"], ["Examination"]],
    [["渴"], ["kě"], ["thirsty"]],
    [["可爱"], ["kě’ài"], ["Lovely"]],
    [["可能"], ["kěnéng"], ["Probably"]],
    [["可以"], ["kěyǐ"], ["Sure"]],
    [["刻"], ["kè"], ["moment"]],
    [["课"], ["kè"], ["class, course"]],
    [["客人"], ["kèrén"], ["Guest"]],
    [["空调"], ["kōngtiáo"], ["air conditioning / air conditioner"]],
    [["口"], ["kǒu"], ["mouth"]],
    [["哭"], ["kū"], ["cry"]],
    [["裤子"], ["kùzi"], ["trousers"]],
    [["块"], ["kuài"], ["block"]],
    [["快"], ["kuài"], ["fast"]],
    [["快乐"], ["kuàilè"], ["happy"]],
    [["筷子"], ["kuàizi"], ["chopsticks"]],
    [["来"], ["lái"], ["come"]],
    [["蓝"], ["lán"], ["blue"]],
    [["老"], ["lǎo"], ["old"]],
    [["老师"], ["lǎoshī"], ["Teacher"]],
    [["了"], ["le"], [""]],
    [["累"], ["lèi"], ["tired"]],
    [["冷"], ["lěng"], ["cold"]],
    [["离"], ["lí"], ["to leave"]],
    [["离开"], ["líkāi"], ["leave"]],
    [["里"], ["lǐ"], ["in"]],
    [["礼物"], ["lǐwù"], ["gift"]],
    [["历史"], ["lìshǐ"], ["History"]],
    [["脸"], ["liǎn"], ["face"]],
    [["练习"], ["liànxí"], ["Practice"]],
    [["两"], ["liǎng"], ["Two"]],
    [["辆"], ["liàng"], ["classifier for vehicles"]],
    [["了解"], ["liǎojiě"], ["to understand"]],
    [["邻居"], ["línjū"], ["neighbor"]],
    [["零"], ["líng"], ["Zero"]],
    [["六"], ["liù"], ["Six"]],
    [["楼"], ["lóu"], ["floor"]],
    [["路"], ["lù"], ["road"]],
    [["旅游"], ["lǚyóu"], ["Tourism"]],
    [["绿"], ["lǜ"], ["green"]],
    [["妈妈"], ["māma"], ["Mom"]],
    [["马"], ["mǎ"], ["Horse"]],
    [["马上"], ["mǎshàng"], ["Right off"]],
    [["吗"], ["ma"], [""]],
    [["买"], ["mǎi"], ["buy"]],
    [["卖"], ["mài"], ["sell"]],
    [["满意"], ["mǎnyì"], ["satisfied"]],
    [["慢"], ["màn"], ["slow"]],
    [["忙"], ["máng"], ["busy"]],
    [["猫"], ["māo"], ["cat"]],
    [["帽子"], ["màozi"], ["Hat"]],
    [["没"], ["méi"], ["no"]],
    [["没关系"], ["méiguānxi"], ["No problem"]],
    [["每"], ["měi"], ["each"]],
    [["妹妹"], ["mèimei"], ["Younger sister"]],
    [["门"], ["mén"], ["door"]],
    [["米"], ["mǐ"], ["rice"]],
    [["米饭"], ["mǐfàn"], ["Steamed Rice"]],
    [["面包"], ["miànbāo"], ["Bread"]],
    [["面条"], ["miàntiáo"], ["noodle"]],
    [["明白"], ["míngbai"], ["clear"]],
    [["明天"], ["míngtiān"], ["Tomorrow"]],
    [["名字"], ["míngzi"], ["Name"]],
    [["拿"], ["ná"], ["take"]],
    [["哪"], ["nǎ"], ["where"]],
    [["那"], ["nà"], ["there"]],
    [["奶奶"], ["nǎinai"], ["grandma"]],
    [["南"], ["nán"], ["south"]],
    [["男人"], ["nánrén"], ["Man"]],
    [["难"], ["nán"], ["difficult; to blame"]],
    [["难过"], ["nánguò"], ["sad"]],
    [["呢"], ["ne"], [""]],
    [["能"], ["néng"], ["can"]],
    [["你"], ["nǐ"], ["you"]],
    [["年"], ["nián"], ["year"]],
    [["年级"], ["niánjí"], ["grade"]],
    [["年轻"], ["niánqīng"], ["Young"]],
    [["鸟"], ["niǎo"], ["bird"]],
    [["您"], ["nín"], ["you"]],
    [["牛奶"], ["niúnǎi"], ["milk"]],
    [["努力"], ["nǔlì"], ["Strive"]],
    [["女儿"], ["nǚ’ér"], ["daughter"]],
    [["女人"], ["nǚrén"], ["woman"]],
    [["爬山"], ["páshān"], ["Mountain climbing"]],
    [["盘子"], ["pánzi"], ["plate"]],
    [["旁边"], ["pángbiān"], ["Side"]],
    [["胖"], ["pàng"], ["fat"]],
    [["跑步"], ["pǎobù"], ["Run"]],
    [["朋友"], ["péngyou"], ["Friend"]],
    [["啤酒"], ["píjiǔ"], ["Beer"]],
    [["便宜"], ["piányi"], ["Cheap"]],
    [["票"], ["piào"], ["ticket"]],
    [["漂亮"], ["piàoliang"], ["beautiful, pretty"]],
    [["苹果"], ["píngguǒ"], ["Apple"]],
    [["葡萄"], ["pútao"], ["Grape"]],
    [["普通话"], ["pǔtōnghuà"], ["Mandarin"]],
    [["七"], ["qī"], ["Seven"]],
    [["妻子"], ["qīzi"], ["Wife"]],
    [["其实"], ["qíshí"], ["actually"]],
    [["其他"], ["qítā"], ["Other"]],
    [["骑"], ["qí"], ["to ride"]],
    [["奇怪"], ["qíguài"], ["strange"]],
    [["起床"], ["qǐchuáng"], ["Get up"]],
    [["千"], ["qiān"], ["thousand"]],
    [["铅笔"], ["qiānbǐ"], ["pencil"]],
    [["钱"], ["qián"], ["money"]],
    [["前面"], ["qiánmiàn"], ["Front"]],
    [["清楚"], ["qīngchu"], ["clear"]],
    [["晴"], ["qíng"], ["Sunny"]],
    [["请"], ["qǐng"], ["please"]],
    [["秋"], ["qiū"], ["autumn"]],
    [["去"], ["qù"], ["go"]],
    [["去年"], ["qùnián"], ["Last year"]],
    [["裙子"], ["qúnzi"], ["skirt"]],
    [["然后"], ["ránhòu"], ["Then"]],
    [["让"], ["ràng"], ["Give Way"]],
    [["热"], ["rè"], ["heat"]],
    [["热情"], ["rèqíng"], ["Enthusiasm"]],
    [["人"], ["rén"], ["people"]],
    [["认识"], ["rènshi"], ["know"]],
    [["认为"], ["rènwéi"], ["think"]],
    [["认真"], ["rènzhēn"], ["earnest / serious"]],
    [["日"], ["rì"], ["day"]],
    [["容易"], ["róngyì"], ["easily"]],
    [["如果"], ["rúguǒ"], ["If"]],
    [["三"], ["sān"], ["Three"]],
    [["伞"], ["sǎn"], ["umbrella"]],
    [["商店"], ["shāngdiàn"], ["Shop"]],
    [["上"], ["shàng"], ["upper"]],
    [["上班"], ["shàngbān"], ["go to work"]],
    [["上网"], ["shàngwǎng"], ["Surf the Internet"]],
    [["上午"], ["shàngwǔ"], ["morning"]],
    [["少"], ["shǎo"], ["less"]],
    [["谁"], ["shéi"], ["who"]],
    [["身体"], ["shēntǐ"], ["body"]],
    [["什么"], ["shénme"], ["What"]],
    [["生病"], ["shēngbìng"], ["Fall ill"]],
    [["生气"], ["shēngqì"], ["to get angry / to take offense / angry / vitality / liveliness"]],
    [["生日"], ["shēngrì"], ["Birthday"]],
    [["声音"], ["shēngyīn"], ["voice"]],
    [["十"], ["shí"], ["Ten"]],
    [["时候"], ["shíhou"], ["time"]],
    [["时间"], ["shíjiān"], ["time"]],
    [["使"], ["shǐ"], ["to send"]],
    [["是"], ["shì"], ["yes"]],
    [["世界"], ["shìjiè"], ["world"]],
    [["事情"], ["shìqing"], ["Thing"]],
    [["手表"], ["shǒubiǎo"], ["Wrist Watch"]],
    [["手机"], ["shǒujī"], ["Mobile phone"]],
    [["瘦"], ["shòu"], ["thin"]],
    [["书"], ["shū"], ["book"]],
    [["舒服"], ["shūfu"], ["comfortable"]],
    [["叔叔"], ["shūshu"], ["uncle"]],
    [["树"], ["shù"], ["tree"]],
    [["数学"], ["shùxué"], ["Mathematics"]],
    [["刷牙"], ["shuāyá"], ["Brush one’s teeth"]],
    [["双"], ["shuāng"], ["double / two / pair"]],
    [["水"], ["shuǐ"], ["water"]],
    [["水果"], ["shuǐguǒ"], ["Fruits"]],
    [["水平"], ["shuǐpíng"], ["level"]],
    [["睡觉"], ["shuìjiào"], ["sleep"]],
    [["说话"], ["shuōhuà"], ["speak"]],
    [["司机"], ["sījī"], ["Driver"]],
    [["四"], ["sì"], ["Four"]],
    [["送"], ["sòng"], ["give"]],
    [["虽然"], ["suīrán"], ["although"]],
    [["岁"], ["suì"], ["year"]],
    [["所以"], ["suǒyǐ"], ["therefore"]],
    [["他"], ["tā"], ["he"]],
    [["她"], ["tā"], ["she"]],
    [["它"], ["tā"], ["it"]],
    [["太"], ["tài"], ["too"]],
    [["太阳"], ["tàiyáng"], ["sunlight"]],
    [["糖"], ["táng"], ["sugar"]],
    [["特别"], ["tèbié"], ["Especially"]],
    [["疼"], ["téng"], ["to be sore; to love dearly"]],
    [["踢足球"], ["tīzúqiú"], ["Play football"]],
    [["题"], ["tí"], ["topic"]],
    [["提高"], ["tígāo"], ["increase"]],
    [["体育"], ["tǐyù"], ["Sports"]],
    [["天气"], ["tiānqì"], ["weather"]],
    [["甜"], ["tián"], ["sweet"]],
    [["条"], ["tiáo"], ["classifier for long things"]],
    [["跳舞"], ["tiàowǔ"], ["to dance"]],
    [["听"], ["tīng"], ["hear"]],
    [["同事"], ["tóngshì"], ["Colleague"]],
    [["同学"], ["tóngxué"], ["Classmate"]],
    [["同意"], ["tóngyì"], ["Agree"]],
    [["头发"], ["tóufa"], ["Hair"]],
    [["突然"], ["tūrán"], ["sudden / abrupt / unexpected"]],
    [["图书馆"], ["túshūguǎn"], ["Library"]],
    [["腿"], ["tuǐ"], ["leg"]],
    [["外"], ["wài"], ["abroad"]],
    [["完"], ["wán"], ["finish"]],
    [["完成"], ["wánchéng"], ["complete"]],
    [["玩"], ["wán"], ["play"]],
    [["碗"], ["wǎn"], ["bowl"]],
    [["晚上"], ["wǎnshang"], ["Night"]],
    [["万"], ["wàn"], ["ten thousand"]],
    [["忘记"], ["wàngjì"], ["forget"]],
    [["喂"], ["wèi"], ["feed"]],
    [["为"], ["wèi"], ["by"]],
    [["为了"], ["wèile"], ["in order to"]],
    [["为什么"], ["wèishénme"], ["Why"]],
    [["位"], ["wèi"], ["place / position / seat"]],
    [["文化"], ["wénhuà"], ["Culture"]],
    [["问"], ["wèn"], ["ask"]],
    [["问题"], ["wèntí"], ["problem"]],
    [["我"], ["wǒ"], ["I"]],
    [["我们"], ["wǒmen"], ["We"]],
    [["五"], ["wǔ"], ["Five"]],
    [["西"], ["xī"], ["west"]],
    [["西瓜"], ["xīguā"], ["watermelon"]],
    [["希望"], ["xīwàng"], ["hope"]],
    [["习惯"], ["xíguàn"], ["Habit"]],
    [["洗"], ["xǐ"], ["wash"]],
    [["洗手间"], ["xǐshǒujiān"], ["Restroom"]],
    [["洗澡"], ["xǐzǎo"], ["to ake a shower"]],
    [["喜欢"], ["xǐhuan"], ["to like"]],
    [["下"], ["xià"], ["lower"]],
    [["下午"], ["xiàwǔ"], ["Afternoon"]],
    [["下雨"], ["xiàyǔ"], ["rain"]],
    [["夏"], ["xià"], ["summer"]],
    [["先"], ["xiān"], ["before"]],
    [["先生"], ["xiānsheng"], ["Sir"]],
    [["现在"], ["xiànzài"], ["Now"]],
    [["香蕉"], ["xiāngjiāo"], ["Banana"]],
    [["相同"], ["xiāngtóng"], ["identical"]],
    [["相信"], ["xiāngxìn"], ["believe"]],
    [["想"], ["xiǎng"], ["think"]],
    [["向"], ["xiàng"], ["towards"]],
    [["像"], ["xiàng"], ["image"]],
    [["小"], ["xiǎo"], ["Small"]],
    [["小姐"], ["xiǎojiě"], ["Miss"]],
    [["小时"], ["xiǎoshí"], ["hour"]],
    [["小心"], ["xiǎoxīn"], ["to be careful"]],
    [["笑"], ["xiào"], ["laugh"]],
    [["校长"], ["xiàozhǎng"], ["Principal"]],
    [["些"], ["xiē"], ["some"]],
    [["鞋"], ["xié"], ["shoes"]],
    [["写"], ["xiě"], ["write"]],
    [["谢谢"], ["xièxie"], ["Thank you"]],
    [["新"], ["xīn"], ["new"]],
    [["新闻"], ["xīnwén"], ["Journalism"]],
    [["新鲜"], ["xīnxiān"], ["fresh"]],
    [["信"], ["xìn"], ["letter"]],
    [["星期"], ["xīngqī"], ["week"]],
    [["行李箱"], ["xínglixiāng"], ["Trunk"]],
    [["姓"], ["xìng"], ["surname"]],
    [["兴趣"], ["xìngqù"], ["Interest"]],
    [["熊猫"], ["xióngmāo"], ["Panda"]],
    [["休息"], ["xiūxi"], ["Rest"]],
    [["需要"], ["xūyào"], ["Need"]],
    [["选择"], ["xuǎnzé"], ["Choice"]],
    [["学生"], ["xuésheng"], ["Student"]],
    [["学习"], ["xuéxí"], ["Study"]],
    [["学校"], ["xuéxiào"], ["School"]],
    [["雪"], ["xuě"], ["Snow"]],
    [["颜色"], ["yánsè"], ["colour"]],
    [["眼镜"], ["yǎnjìng"], ["glasses"]],
    [["眼睛"], ["yǎnjing"], ["Eye"]],
    [["羊肉"], ["yángròu"], ["mutton"]],
    [["要求"], ["yāoqiú"], ["to request / to require / to ask / to demand"]],
    [["药"], ["yào"], ["drug"]],
    [["要"], ["yào"], ["want"]],
    [["爷爷"], ["yéye"], ["grandpa"]],
    [["也"], ["yě"], ["also"]],
    [["一"], ["yī"], ["one"]],
    [["衣服"], ["yīfu"], ["clothes"]],
    [["医生"], ["yīshēng"], ["Doctor"]],
    [["医院"], ["yīyuàn"], ["Hospital"]],
    [["一定"], ["yídìng"], ["Certain"]],
    [["一共"], ["yígòng"], ["Altogether"]],
    [["一会儿"], ["yíhuìr"], ["A little while"]],
    [["一样"], ["yíyàng"], ["equally"]],
    [["以后"], ["yǐhòu"], ["In the future"]],
    [["以前"], ["yǐqián"], ["before"]],
    [["以为"], ["yǐwéi"], ["Think"]],
    [["已经"], ["yǐjīng"], ["Already"]],
    [["椅子"], ["yǐzi"], ["Chair"]],
    [["一般"], ["yìbān"], ["commonly"]],
    [["一边"], ["yìbiān"], ["One side"]],
    [["一起"], ["yìqǐ"], ["together"]],
    [["一直"], ["yìzhí"], ["always"]],
    [["意思"], ["yìsi"], ["Meaning"]],
    [["阴"], ["yīn"], ["Yin"]],
    [["因为"], ["yīnwèi"], ["because"]],
    [["音乐"], ["yīnyuè"], ["Music"]],
    [["银行"], ["yínháng"], ["Bank"]],
    [["应该"], ["yīnggāi"], ["Should"]],
    [["影响"], ["yǐngxiǎng"], ["Influence"]],
    [["用"], ["yòng"], ["use"]],
    [["游戏"], ["yóuxì"], ["Game"]],
    [["游泳"], ["yóuyǒng"], ["Swimming"]],
    [["有"], ["yǒu"], ["have"]],
    [["有名"], ["yǒumíng"], ["Famous"]],
    [["又"], ["yòu"], ["also"]],
    [["右边"], ["yòubian"], ["Right"]],
    [["鱼"], ["yú"], ["fish"]],
    [["遇到"], ["yùdào"], ["to meet"]],
    [["元"], ["yuán"], ["element"]],
    [["远"], ["yuǎn"], ["far"]],
    [["愿意"], ["yuànyì"], ["Be willing"]],
    [["月"], ["yuè"], ["month"]],
    [["月亮"], ["yuèliang"], ["Moon"]],
    [["越"], ["yuè"], ["The more"]],
    [["云"], ["yún"], ["cloud"]],
    [["运动"], ["yùndòng"], ["motion"]],
    [["在"], ["zài"], ["stay"]],
    [["再"], ["zài"], ["again"]],
    [["再见"], ["zàijiàn"], ["goodbye / see you again later"]],
    [["早上"], ["zǎoshang"], ["Morning"]],
    [["怎么"], ["zěnme"], ["How"]],
    [["怎么样"], ["zěnmeyàng"], ["How"]],
    [["站"], ["zhàn"], ["station"]],
    [["张"], ["zhāng"], ["Zhang"]],
    [["长"], ["zhǎng"], ["long"]],
    [["丈夫"], ["zhàngfu"], ["husband"]],
    [["着急"], ["zháojí"], ["Worry"]],
    [["找"], ["zhǎo"], ["to try to find / to look for"]],
    [["照顾"], ["zhàogù"], ["look after"]],
    [["照片"], ["zhàopiàn"], ["Photo"]],
    [["照相机"], ["zhàoxiàngjī"], ["Camera"]],
    [["这"], ["zhè"], ["Here"]],
    [["着"], ["zhe"], ["means"]],
    [["真"], ["zhēn"], ["really"]],
    [["正在"], ["zhèngzài"], ["right in the middle of doing"]],
    [["知道"], ["zhīdào"], ["know"]],
    [["只"], ["zhǐ"], ["only"]],
    [["中国"], ["zhōngguó"], ["China"]],
    [["中间"], ["zhōngjiān"], ["Middle"]],
    [["中午"], ["zhōngwǔ"], ["Noon"]],
    [["终于"], ["zhōngyú"], ["finally"]],
    [["种"], ["zhǒng"], ["species"]],
    [["重要"], ["zhòngyào"], ["important"]],
    [["周末"], ["zhōumò"], ["Weekend"]],
    [["主要"], ["zhǔyào"], ["main / principal"]],
    [["住"], ["zhù"], ["live"]],
    [["祝"], ["zhù"], ["to wish"]],
    [["注意"], ["zhùyì"], ["to pay attention to / to take note of"]],
    [["准备"], ["zhǔnbèi"], ["Get ready"]],
    [["桌子"], ["zhuōzi"], ["table"]],
    [["字"], ["zì"], ["word"]],
    [["字典"], ["zìdiǎn"], ["dictionary"]],
    [["自己"], ["zìjǐ"], ["Own"]],
    [["自行车"], ["zìxíngchē"], ["Bicycle"]],
    [["总是"], ["zǒngshì"], ["always"]],
    [["走"], ["zǒu"], ["go"]],
    [["最"], ["zuì"], ["most"]],
    [["最近"], ["zuìjìn"], ["Lately"]],
    [["昨天"], ["zuótiān"], ["yesterday"]],
    [["左边"], ["zuǒbian"], ["left"]],
    [["坐"], ["zuò"], ["sit"]],
    [["做"], ["zuò"], ["do"]],
    [["作业"], ["zuòyè"], ["homework"]],
    [["作用"], ["zuòyòng"], ["effect"]]
];
*/